// plugins/tokens.ts

import type { Plugin }                           from "vite";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname }                       from "path";
import vm                                         from "node:vm";
import type { TokenBlock }                        from "../src/design/shared/primitives.definitions";

const DEFS_FILE   = "src/design/shared/primitives.definitions.ts";
const SCALES_FILE = "src/design/shared/definitions/scales.ts";
const CSS_OUT     = "src/design/styles/tokens.generated.css";
const TS_OUT      = "src/design/shared/primitives.tokens.generated.ts";

// ─── CSS GENERATOR ───────────────────────────────────────────

function buildCSS(blocks: TokenBlock[]): string {
  const header = [
    "/* ==========================================================",
    "   tokens.generated.css",
    "   Auto-generated by plugins/tokens.ts",
    "   DO NOT EDIT — edit primitives.definitions.ts instead",
    "   ========================================================== */",
  ].join("\n");

  const rules = blocks.map(({ selector, vars, mediaQuery }) => {
    const pad          = mediaQuery ? "    " : "  ";
    const declarations = Object.entries(vars)
      .map(([key, value]) => `${pad}--${key}: ${value};`)
      .join("\n");
    const rule = `${mediaQuery ? "  " : ""}${selector} {\n${declarations}\n${mediaQuery ? "  " : ""}}`;
    return mediaQuery ? `${mediaQuery} {\n${rule}\n}` : rule;
  });

  return [header, "", ...rules].join("\n\n") + "\n";
}

// ─── TS GENERATOR ────────────────────────────────────────────

/** SCREAMING_SNAKE → PascalCase: COLOR_ROLE → ColorRole */
function toPascalCase(name: string): string {
  return name
    .split("_")
    .map(w => w[0].toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

/** Quote a scale key if it isn't a valid bare JS identifier. */
function quoteKey(k: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : `"${k}"`;
}

function buildTS(scaleDefs: Record<string, Record<string, string | null>>): string {
  const lines: string[] = [
    "// ================================================================",
    "//  primitives.tokens.generated.ts",
    "//  AUTO-GENERATED — do not edit.",
    "//  Source: src/design/shared/primitives.definitions.ts → SCALE_DEFS",
    "//  Regenerated automatically when primitives.definitions.ts is saved.",
    "// ================================================================",
    "",
    `import { scale } from "~/shared/tokens";`,
    "",
  ];

  for (const [name, entries] of Object.entries(scaleDefs)) {
    const typeName = toPascalCase(name);
    const keys     = Object.keys(entries);

    // Align values by longest key for readability
    const maxKeyLen = Math.max(...keys.map(k => quoteKey(k).length));

    const pairs = keys
      .map(k => {
        const qk      = quoteKey(k);
        const pad      = " ".repeat(maxKeyLen - qk.length + 1);
        const val      = entries[k];
        const serialized = val === null ? "null" : `"${val}"`;
        return `  ${qk}:${pad}${serialized},`;
      })
      .join("\n");

    lines.push(`export const ${name} = scale({\n${pairs}\n});\n`);
    lines.push(`export type ${typeName} = keyof typeof ${name};\n`);
  }

  return lines.join("\n");
}

// ─── LOCAL IMPORT INLINER ────────────────────────────────────
// The vm has no module system, so local relative imports must be
// inlined before stripping. Handles:
//   import { ... } from './x'
//   import * as ns from './x'
//   export * from './x'          ← barrel re-exports
//   export { ... } from './x'
// Recurses so sub-files can import from each other.
// External imports (node_modules, aliases) are left for stripTS to remove.

const LOCAL_REF_RE =
  /^(?:import|export)\s+(?:type\s+)?(?:\*(?:\s+as\s+\w+)?|\{[\s\S]*?\}|\w+)?\s*from\s+['"](\.[^'"]+)['"]\s*;?/gm;

function resolveLocalPath(importPath: string, fromDir: string): string | null {
  const candidates = [
    resolve(fromDir, importPath + ".ts"),
    resolve(fromDir, importPath + "/index.ts"),
    resolve(fromDir, importPath),
  ];
  for (const c of candidates) {
    try { readFileSync(c); return c; } catch { /* try next */ }
  }
  return null;
}

function inlineLocalImports(
  src: string,
  dir: string,
  visited = new Set<string>(),
): string {
  const chunks: string[] = [];

  // Find all local imports, inline their content first (dependency order)
  for (const match of src.matchAll(LOCAL_REF_RE)) {
    const importPath = match[1];
    const resolved   = resolveLocalPath(importPath, dir);
    if (!resolved || visited.has(resolved)) continue;
    visited.add(resolved);
    const content = readFileSync(resolved, "utf-8");
    chunks.push(inlineLocalImports(content, dirname(resolved), visited));
  }

  // Append the current file with local import statements removed
  chunks.push(src.replace(LOCAL_REF_RE, ""));
  return chunks.join("\n");
}

// ─── DEFINITIONS LOADER ──────────────────────────────────────
// Reads definitions.ts, strips TypeScript syntax, converts
// `const`/`export const` to `var` so declarations become
// properties on the vm context.
//
// Why var?  `const` and `let` are block-scoped and don't attach
// to the vm context object. `var` declarations in vm code DO
// become properties on the context — that's how we extract them.
//
// Import statements are stripped: the definitions file may import
// sub-files (e.g. `./definitions`) but the vm context has no module
// system. Any variables those imports would have provided must be
// defined inline in the file instead, OR the sub-files must be
// inlined here before stripping. For now: strip imports and require
// that all token values used by TOKEN_BLOCKS and SCALE_DEFS are
// defined inline in primitives.definitions.ts (imports are for types only).

function stripTS(src: string): string {
  return src
    // strip remaining import statements (external modules, aliases)
    .replace(/^import\s+(?:type\s+)?[\s\S]*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, "")
    // strip bare re-exports: export * from '...', export { } from '...'
    .replace(/^export\s+(?:\*|\{[^}]*\})\s+from\s+['"][^'"]+['"]\s*;?$/gm, "")
    // strip named re-exports without source: export { foo, bar }
    .replace(/^export\s+\{[^}]*\}\s*;?$/gm, "")
    .replace(/ as const\b/g, "")
    // satisfies with generic types — match to end of line
    .replace(/ satisfies [^\n]+/g, "")
    // type annotations before = (e.g. : Record<string, string>)
    .replace(/: [A-Z]\w*(?:<[^>]*>)?(?:\[\])?(?=\s*=)/g, "")
    // export interface blocks
    .replace(/^export interface \w+ \{[\s\S]*?\n\}\n?/gm, "")
    // type-only exports
    .replace(/^export type .+$/gm, "")
    // export const / const → var so they attach to the vm context
    .replace(/^export const /gm, "var ")
    .replace(/^const /gm, "var ");
}

function loadBlocks(defsPath: string): TokenBlock[] {
  const src     = readFileSync(defsPath, "utf-8");
  const inlined = inlineLocalImports(src, dirname(defsPath));
  const js      = stripTS(inlined);
  const context = vm.createContext({});

  try {
    vm.runInContext(js, context);
  } catch (err) {
    throw new Error(
      `[dezign8-tokens] Failed to evaluate definitions:\n${String(err)}\n\n` +
      `Stripped output (first 300 chars):\n${js.slice(0, 300)}`,
    );
  }

  const blocks = context.TOKEN_BLOCKS as TokenBlock[] | undefined;
  if (!Array.isArray(blocks)) {
    throw new Error(
      "[dezign8-tokens] TOKEN_BLOCKS not found — " +
      "ensure primitives.definitions.ts exports TOKEN_BLOCKS",
    );
  }
  return blocks;
}

// scales.ts is a pure data file — no imports, no dependencies.
// The vm approach works cleanly: SCALE_DEFS lands on the context as-is.
function loadScaleDefs(
  scalesPath: string,
): Record<string, Record<string, string | null>> {
  const src     = readFileSync(scalesPath, "utf-8");
  const js      = stripTS(src);
  const context = vm.createContext({});

  try {
    vm.runInContext(js, context);
  } catch (err) {
    throw new Error(
      `[dezign8-tokens] Failed to evaluate scales:\n${String(err)}\n\n` +
      `Stripped output (first 300 chars):\n${js.slice(0, 300)}`,
    );
  }

  const defs = context.SCALE_DEFS as Record<string, Record<string, string | null>> | undefined;
  if (!defs || typeof defs !== "object") {
    throw new Error(
      "[dezign8-tokens] SCALE_DEFS not found — " +
      "ensure definitions/scales.ts exports SCALE_DEFS",
    );
  }
  return defs;
}

// ─── GENERATE & WRITE ────────────────────────────────────────

function generate(defsPath: string, scalesPath: string, cssOut: string, tsOut: string): void {
  // CSS from TOKEN_BLOCKS
  const blocks    = loadBlocks(defsPath);
  const css       = buildCSS(blocks);
  const totalVars = blocks.reduce((n, b) => n + Object.keys(b.vars).length, 0);
  mkdirSync(dirname(cssOut), { recursive: true });
  writeFileSync(cssOut, css, "utf-8");
  console.log(`[dezign8-tokens] ${cssOut} — ${blocks.length} blocks, ${totalVars} vars`);

  // TS from SCALE_DEFS
  const scaleDefs = loadScaleDefs(scalesPath);
  const ts        = buildTS(scaleDefs);
  mkdirSync(dirname(tsOut), { recursive: true });
  writeFileSync(tsOut, ts, "utf-8");
  console.log(`[dezign8-tokens] ${tsOut} — ${Object.keys(scaleDefs).length} scales`);
}

// ─── PLUGIN ──────────────────────────────────────────────────

export function tokensPlugin(): Plugin {
  let defsPath:   string;
  let scalesPath: string;
  let cssOut:     string;
  let tsOut:      string;

  return {
    name:    "dezign8-tokens",
    enforce: "pre",

    configResolved(config) {
      defsPath   = resolve(config.root, DEFS_FILE);
      scalesPath = resolve(config.root, SCALES_FILE);
      cssOut     = resolve(config.root, CSS_OUT);
      tsOut      = resolve(config.root, TS_OUT);
    },

    buildStart() {
      generate(defsPath, scalesPath, cssOut, tsOut);
    },

    handleHotUpdate({ file }) {
      if (file === defsPath || file === scalesPath) {
        generate(defsPath, scalesPath, cssOut, tsOut);
      }
    },
  };
}