export const PRINT_THEME_TOKENS: Record<string, string> = {
  "bg--0":            "white",
  "bg--1":            "white",
  "bg--2":            "white",
  "bg--3":            "white",
  "bg--4":            "white",
  "bg--5":            "white",
  "text--primary":    "black",
  "text--secondary":  "oklch(30% 0 0)",
  "text--tertiary":   "oklch(45% 0 0)",
  "shadow--xs":       "none",
  "shadow--sm":       "none",
  "shadow--md":       "none",
  "shadow--lg":       "none",
  "shadow--xl":       "none",
  "shadow--inset":    "none",
  "glass--shadow":    "none",
  "glass--highlight": "transparent",
};
