export const SEMANTIC_SIZE_TOKENS: Record<string, string> = {
  // Fluid font sizes
  "fs--3xs": "calc(var(--size-0) * 0.75)",
  "fs--2xs": "var(--size-0)", 
  "fs--xs":  "var(--size-1)", 
  "fs--sm":  "var(--size-2)",
  "fs--md":  "var(--size-3)", 
  "fs--lg":  "var(--size-4)", 
  "fs--xl":  "var(--size-5)",
  "fs--2xl": "var(--size-6)", 
  "fs--3xl": "var(--size-7)", 
  "fs--4xl": "var(--size-8)",
  "fs--5xl": "var(--size-9)",
  "fs--6xl": "var(--size-10)",

  // Fixed font sizes (UI labels)
  "label--3xs": "calc(var(--size-02) * 0.75)",
  "label--2xs": "var(--size-02)", 
  "label--xs":  "var(--size-03)", 
  "label--sm":  "var(--size-04)",
  "label--md":  "var(--size-05)", 
  "label--lg":  "var(--size-06)", 
  "label--xl":  "var(--size-07)",
  "label--2xl": "var(--size-08)", 
  "label--3xl": "var(--size-09)", 
  "label--4xl": "var(--size-8)",
  "label--5xl": "var(--size-9)",
  "label--6xl": "var(--size-10)",

  "fsf--3xs": "calc(var(--size-01) * 0.75)",
  "fsf--2xs": "var(--size-01)", 
  "fsf--xs":  "var(--size-02)", 
  "fsf--sm":  "var(--size-03)",
  "fsf--md":  "var(--size-05)", 
  "fsf--lg":  "var(--size-06)", 
  "fsf--xl":  "var(--size-07)",
  "fsf--2xl": "var(--size-08)",
  "fsf--3xl": "var(--size-09)",
  "fsf--4xl": "var(--size-8)",
  "fsf--5xl": "var(--size-9)",
  "fsf--6xl": "var(--size-10)",


  // Interior spacing — padding, component gaps
  "space-in--4xs": "calc(var(--size-00) / 2)",
  "space-in--3xs": "calc(var(--size-01) / 2)",
  "space-in--2xs":      "var(--size-00)",
  "space-in--xs":       "var(--size-01)",
  "space-in--sm":       "var(--size-02)",
  "space-in--md":       "var(--size-05)",
  "space-in--lg":       "var(--size-07)",
  "space-in--xl":       "var(--size-08)",
  "space-in--2xl":      "var(--size-09)",
  "space-in--3xl":      "var(--size-10)",
  "space-in--4xl":      "var(--size-12)",
  "space-in--5xl":      "var(--size-15)",
  "space-in--6xl":      "var(--size-17)",

  "padding--4xs": "var(--space-in--4xs)",
  "padding--3xs": "var(--space-in--3xs)",
  "padding--2xs": "var(--space-in--2xs)",
  "padding--xs":  "var(--space-in--xs)",
  "padding--sm":  "var(--space-in--sm)",
  "padding--md":  "var(--space-in--md)",
  "padding--lg":  "var(--space-in--lg)",
  "padding--xl":  "var(--space-in--xl)",
  "padding--2xl": "var(--space-in--2xl)",
  "padding--3xl": "var(--space-in--3xl)",
  "padding--4xl": "var(--space-in--4xl)",
  "padding--5xl": "var(--space-in--5xl)",
  "padding--6xl": "var(--space-in--6xl)",

  // Exterior spacing — section margins, layout gaps
  "space-out--3xs": "calc(var(--size-3) / 2)",
  "space-out--2xs":      "var(--size-0)",
  "space-out--xs":       "var(--size-2)",
  "space-out--sm":       "var(--size-4)",
  "space-out--md":       "var(--size-6)",
  "space-out--lg":       "var(--size-8)",
  "space-out--xl":       "var(--size-10)",
  "space-out--2xl":      "var(--size-12)",
  "space-out--3xl":      "var(--size-15)",
  "space-out--4xl":      "var(--size-16)",
  "space-out--5xl":      "var(--size-17)",
  "space-out--6xl":      "calc(var(--size-17) * 1.5)",

  "margin--3xs": "var(--space-out--3xs)",
  "margin--2xs": "var(--space-out--2xs)",
  "margin--xs":  "var(--space-out--xs)",
  "margin--sm":  "var(--space-out--sm)",
  "margin--md":  "var(--space-out--md)",
  "margin--lg":  "var(--space-out--lg)",
  "margin--xl":  "var(--space-out--xl)",
  "margin--2xl": "var(--space-out--2xl)",
  "margin--3xl": "var(--space-out--3xl)",
  "margin--4xl": "var(--space-out--4xl)",
  "margin--5xl": "var(--space-out--5xl)",
  "margin--6xl": "var(--space-out--6xl)",

  // Border radius
  "radius--3xs":  "calc(var(--size-00) / 4)",
  "radius--2xs":  "calc(var(--size-00) / 3)",
  "radius--xs":   "calc(var(--size-00) / 2)",
  "radius--sm":        "var(--size-00)",
  "radius--md":        "var(--size-01)",
  "radius--lg":        "var(--size-02)",
  "radius--xl":        "var(--size-04)",
  "radius--2xl":       "var(--size-07)",
  "radius--3xl":       "var(--size-08)",
  "radius--4xl":       "var(--size-09)",
  "radius--5xl":       "var(--size-10)",
  "radius--6xl":       "var(--size-12)",
  "radius--full":      "var(--size-full)",

  // Containers
  "container--sm":   "var(--container-sm)",  
  "container--md":   "var(--container-md)",
  "container--lg":   "var(--container-lg)", 
  "container--xl":   "var(--container-xl)",
  "container--2xl":  "var(--container-2xl)", 
  "container--full": "100%",

  // UI component heights
  "ui-height--5xs":  "var(--size-01)",
  "ui-height--4xs": "var(--size-02)",
  "ui-height--3xs": "var(--size-03)", 
  "ui-height--2xs": "var(--size-04)", 
  "ui-height--xs":  "var(--size-05)",
  "ui-height--sm":  "var(--size-06)", 
  "ui-height--md":  "var(--size-07)",
  "ui-height--lg":  "var(--size-08)", 
  "ui-height--xl":  "var(--size-09)",
  "ui-height--2xl": "var(--size-10)",
  "ui-height--3xl": "var(--size-11)",
  "ui-height--4xl": "var(--size-12)",
  "ui-height--5xl": "var(--size-13)",
  "ui-height--6xl": "var(--size-14)",

  // Icon sizes
  "icon-size--3xs": "calc(var(--size-1) * 0.75)",
  "icon-size--2xs": "var(--size-1)", 
  "icon-size--xs":  "var(--size-2)",
  "icon-size--sm":  "var(--size-3)", 
  "icon-size--md":  "var(--size-4)",
  "icon-size--lg":  "var(--size-6)", 
  "icon-size--xl":  "var(--size-8)",
  "icon-size--2xl": "var(--size-10)",
  "icon-size--3xl": "var(--size-12)",
  "icon-size--4xl": "var(--size-13)",
  "icon-size--5xl": "var(--size-14)",
  "icon-size--6xl": "var(--size-15)",

  "icon--size-3xs": "calc(var(--size-1) * 0.75)",
  "icon--size-2xs": "var(--size-1)", 
  "icon--size-xs":  "var(--size-2)",
  "icon--size-sm":  "var(--size-3)", 
  "icon--size-md":  "var(--size-4)",
  "icon--size-lg":  "var(--size-6)", 
  "icon--size-xl":  "var(--size-8)",
  "icon--size-2xl": "var(--size-10)",
  "icon--size-3xl": "var(--size-12)",
  "icon--size-4xl": "var(--size-13)",
  "icon--size-5xl": "var(--size-14)",
  "icon--size-6xl": "var(--size-15)",
};