// design/shared/base.hook.ts

import type { BaseComponentProps } from "./base.props";
import type { ColorRole }          from "./primitives.tokens";
import { getMotionAttrs }          from "./motion/motion.utils";
import { resolveSpacingStyles }    from "./spacing.props";

export type ClassToken = string | false | null | undefined;
export type StyleToken = string | false | null | undefined;

export interface BaseComposeOptions {
  prefix?:    string;
  className?: ClassToken[];
  style?:     StyleToken[];
  attrs?:     Record<string, unknown>;
  /** Computed disabled state. Emits aria-disabled + data-disabled. Overrides base.disabled. */
  disabled?:  boolean;
  /** Computed loading state. Emits aria-busy + data-loading. Overrides base.loading. */
  loading?:   boolean;
}

/**
 * Composes a space-separated string of CSS class names from a list of class tokens.
 * This function is a utility primarily used within component hooks (e.g., `useButton`, `useIcon`)
 * to assemble the final `class` attribute value for rendered HTML elements.
 *
 * Class tokens are typically generated by the `resolveTokens` utility (from `~/shared/tokens.ts`).
 * `resolveTokens` takes a component's token specification, selected props, and a prefix,
 * returning an object containing `classes: ClassToken[]` and `style: StyleToken[]`.
 *
 * Common consumers:
 * - **Component Hooks**: Almost every component hook (e.g., `src/design/assets/components/icon/icon.hook.ts`,
 *   `src/design/layout/layout.hook.ts`) calls `resolveTokens` and then passes the resulting
 *   `classes` array to `composeClass`.
 * - **`useBaseCompose`**: The output string from `composeClass` is often merged with
 *   other class strings (e.g., from `className` props or BEM modifiers) within `useBaseCompose`
 *   to create the complete `class` attribute for a component's root element.
 *
 * Usage:
 * The `ClassToken` array from `resolveTokens` often contains:
 * - Modifier classes (e.g., `component--modifier`) when a token dimension uses `modifier: true`.
 * - Other dynamically generated class strings.
 * This function filters out any falsy values (null, undefined, false) and joins the remaining
 * tokens with a single space.
 *
 * @param parts - An array of `ClassToken`s, typically sourced from `resolveTokens(TOKENS, props, prefix).classes`.
 * @returns A space-separated string of CSS class names, suitable for the HTML `class` attribute.
 *
 * @example
 * ```typescript
 * // In a component hook (e.g., useIcon)
 * import { resolveTokens } from '~/shared/tokens';
 * import { composeClass } from '~/shared/base.hook';
 *
 * const { classes } = resolveTokens(ICON_TOKENS, { size }, 'icon');
 * const className = composeClass(...classes, 'other-class'); // "icon--md other-class"
 * // ... then applied to an element: <i class={className}></i>
 * ```
 */
export function composeClass(...parts: ClassToken[]): string {
  return parts.filter(Boolean).join(" ");
}

/**
 * Composes a semicolon-separated string of CSS style declarations from a list of style tokens.
 * This function is a utility primarily used within component hooks (e.g., `useButton`, `useIcon`)
 * to assemble the final `style` attribute value for rendered HTML elements.
 *
 * 
 * Style tokens are typically generated by the `resolveTokens` utility (from `~/shared/tokens.ts`).
 * `resolveTokens` takes a component's token specification, selected props, and a prefix,
 * returning an object containing `classes: ClassToken[]` and `style: StyleToken[]`.
 * @example `classes: ["component--modifier", "another-class"]`
 * @see {@link '/home/jk/Code/dezign8/src/shared/base.hook.ts'}    — resolveTokens: resolves props to { Tag, props, selectedProps }
}
 *
 * @example `style: ["--component--key: value;", "color: red;"]`
 *
 * 
 * Common consumers:
 * - **Component Hooks**: Almost every component hook (e.g., `src/design/assets/components/icon/icon.hook.ts`,
 *   `src/design/layout/layout.hook.ts`) calls `resolveTokens` and then passes the resulting
 *   `style` array to `composeStyle`.
 * - **`useBaseCompose`**: The output string from `composeStyle` is often merged with
 * @see https://github.com/dezign8/dezign8/blob/main/src/design/shared/base.hook.ts#L112
 *
 *   other style strings (e.g., from `style` props or other dynamic styles) within `useBaseCompose`
 *   to create the complete `style` attribute for a component's root element.
 * 
 *
 * Usage:
 * The `StyleToken` array from `resolveTokens` often contains:
 * - CSS variable declarations (e.g., `--icon--size: var(--size-md);`)
 * - Other inline style declarations.
 * This function filters out any falsy values (null, undefined, false) and joins the remaining
 * tokens with a semicolon and a space.
 *
 * @param parts - An array of `StyleToken`s, typically sourced from `resolveTokens(TOKENS, props, prefix).style`.
 * @returns A semicolon-separated string of CSS style declarations, suitable for the HTML `style` attribute.
 *
 * @example
 * ```typescript
 * // In a component hook (e.g., useIcon)
 * import { resolveTokens } from '~/shared/tokens';
 * import { composeStyle } from '~/shared/base.hook';
 *
 * const { style } = resolveTokens(ICON_TOKENS, { size: 'md' }, 'icon');
 * @see https://github.com/dezign8/dezign8/blob/main/src/design/assets/components/icon/icon.hook.ts#L22
 *
 * const styleAttribute = composeStyle(...style, 'color: blue;'); // "--icon--size: var(--size-md); color: blue;"
 * // ... then applied to an element: <i style={styleAttribute}></i>
 * ```
 */
export function composeStyle(...parts: StyleToken[]): string {
  return parts.filter(Boolean).join("; ");
}

/**
 * The shared foundation every component hook runs through.
 *
 * Every component in this design system has its own hook (e.g. `useIcon`,
 * `useLayout`, `useFeedback`). Before returning its final props, that hook
 * calls `useBaseCompose` exactly once. `useBaseCompose` takes the
 * component-specific class names and styles the hook has already built,
 * merges them with whatever the _consumer_ (the Astro file or parent
 * component) passed in via `BaseComponentProps`, and returns one unified
 * bundle ready to spread onto the root HTML element.
 *
 * ---
 *
 * ## Parameters
 *
 * | param | what goes here |
 * |---|---|
 * | `options.className` | Array of class tokens this hook has built — BEM block name, modifier classes from `resolveTokens`, any conditional flags. Falsy values are filtered out automatically. |
 * | `options.style` | Array of inline style tokens (CSS-variable assignments) from `resolveTokens`, `resolveColorRole`, or `resolveSpacingStyles`. Joined with `"; "`. |
 * | `options.attrs` | Extra `data-*` or `aria-*` attributes the hook wants to add beyond what the base system provides. |
 * | `options.disabled` | Computed disabled state. When `true`, emits `aria-disabled="true"` and `data-disabled`. Overrides `base.disabled`. |
 * | `options.loading` | Computed loading state. When `true`, emits `aria-busy="true"` and `data-loading`. Overrides `base.loading`. |
 * | `base` | The leftover props from the consumer's spread — everything in `BaseComponentProps` that was not a component-specific prop. Spacing, motion, visual (`v`), `testId`, `bg`, `class`, `style`, etc. |
 *
 * ## Return value
 *
 * | key | type | what it contains |
 * |---|---|---|
 * | `className` | `string` | Final space-separated class string — component classes merged with the consumer's `class` prop. Spread as `class={cls}`. |
 * | `style` | `string` | Final semicolon-separated inline style string — token vars + motion vars + the consumer's `style` prop. |
 * | `attrs` | `object` | All data/aria attributes — from `base`, from `options.attrs`, from motion, from loading/disabled state. Spread with `{...attrs}`. |
 * | `rest` | `object` | Any remaining props (e.g. `id`, `role`, native HTML attributes) that were neither consumed by the hook nor handled by `useBaseCompose`. Spread last so the consumer can still override anything. |
 * | `spacing` | `object` | Spacing props (`p`, `m`, `pt`, `mx`, …) extracted from `base` but **not** applied automatically. The hook must wire these up itself via `resolveSpacingStyles`. |
 *
 * ---
 *
 * ## How components consume this hook
 *
 * There are four patterns, ordered from simplest to most involved.
 *
 * ---
 *
 * ### Pattern 1 — Token classes + token styles, no extras
 *
 * **Used by:** {@link file://./../../assets/components/icon/icon.hook.ts | `useIcon`},
 * `useOverlays`, `useAvatar`, and most leaf-node component hooks.
 *
 * The hook resolves its token dimensions with `resolveTokens`, passes the
 * resulting `classes` and `style` arrays straight in, and spreads everything
 * back onto the element. No extra attrs, no spacing, no color channels.
 *
 * ```ts
 * // icon.hook.ts — simplified
 * const { classes: tokenClasses, style: tokenStyle } =
 *   resolveTokens(ICON_TOKENS, { size, color }, "icon");
 *
 * //  options ──────────────────────────────────── base ───
 * const { className: cls, style, attrs, rest } = useBaseCompose(
 *   {
 *     className: ["icon", ...tokenClasses, className], // "icon icon--md"
 *     style:     tokenStyle,                           // "--icon--size: var(--size-md)"
 *   },
 *   base,  // v, testId, motion, class, style, id, …
 * );
 *
 * return {
 *   name,
 *   props: { class: cls, style: style || undefined, ...attrs, ...rest },
 * };
 * ```
 *
 * **Example input → output:**
 * - Props: `size="lg"`, `testId="my-icon"`, `motion="fade-in"`
 * - `cls` → `"icon icon--lg"`
 * - `style` → `"--icon--size: var(--size-lg); --m--enter-opacity: 0; …"`
 * - `attrs` → `{ "data-testid": "my-icon", "data-motion": "" }`
 * - `rest` → `{}` (everything was consumed)
 *
 * ---
 *
 * ### Pattern 2 — Token classes + token styles + color channels + spacing
 *
 * **Used by:** {@link file://./../../layout/layout.hook.ts | `useLayout`},
 * `useFeedback`, `useData`, `useForms`.
 *
 * Adds two things on top of Pattern 1:
 * 1. **Color role channels** via `resolveColorRole` or `resolveColorChannels` —
 *    a set of seven CSS-variable assignments that let the component's CSS read
 *    semantic color steps without knowing the actual role.
 * 2. **Spacing styles** via `resolveSpacingStyles` — turns shorthand `p`, `mx`,
 *    etc. props into CSS-variable assignments. `useBaseCompose` extracts the
 *    raw spacing props into `spacing` but does NOT apply them; the hook must do
 *    that itself and inject the result into the `style` array.
 *
 * ```ts
 * // layout.hook.ts — simplified
 * const { classes: tokenClasses, style: tokenStyle } =
 *   resolveTokens(LAYOUT_TOKENS, { gap, align, justify }, "layout");
 *
 * const spacingStyle = resolveSpacingStyles(
 *   { p, px, py, pt, pr, pb, pl, m, mx, my, mt, mr, mb, ml },
 *   "layout",
 * );
 *
 * const { className: cls, style, attrs, rest: restAttrs, spacing } = useBaseCompose(
 *   {
 *     className: ["layout", ...tokenClasses, className],
 *     style: [
 *       ...tokenStyle,
 *       ...spacingStyle,                                // ← spacing vars injected here
 *       ...(bg ? resolveColorRole(bg, "layout--bg") : []), // ← 7 color-channel vars
 *     ],
 *   },
 *   base,
 * );
 * ```
 *
 * **Example input → output:**
 * - Props: `gap="md"`, `bg="primary"`, `p="lg"`, `class="my-box"`
 * - `cls` → `"layout layout--gap-md my-box"`
 * - `style` → `"--layout--gap: var(--gap-md); --layout--padding: var(--space-lg); --layout--bg--base: var(--primary--base); …"`
 * - `spacing` → `{ p: "lg", px: undefined, … }` (for introspection; already applied via `spacingStyle`)
 *
 * ---
 *
 * ### Pattern 3 — Passing `options.attrs` for component-specific data attributes
 *
 * **Used by:** {@link file://./../../data/data.hook.ts | `useData`},
 * `useFeedback`.
 *
 * When the component needs its own `data-*` attributes beyond the base system
 * (e.g. `data-empty`, `data-interactive`), the hook builds them as a plain
 * object and passes them in via `options.attrs`. `useBaseCompose` merges these
 * with the base attrs (motion, loading, testId, etc.) in the returned `attrs`.
 *
 * ```ts
 * // data.hook.ts — simplified
 * const { className: cls, style, attrs, rest: restAttrs } = useBaseCompose(
 *   {
 *     className: ["data", ...tokenClasses, className],
 *     style:     [...tokenStyle, ...colorStyle],
 *     attrs: {                                       // ← component-specific attrs
 *       ...(emptyAttr !== undefined ? { "data-empty":       emptyAttr } : {}),
 *       ...(interactive             ? { "data-interactive": "true"    } : {}),
 *       ...(selectable              ? { "data-selectable":  "true"    } : {}),
 *     },
 *   },
 *   base,
 * );
 * ```
 *
 * **Example input → output:**
 * - Props: `empty="No results found"`, `interactive`, `loading`
 * - `attrs` → `{ "data-empty": "No results found", "data-interactive": "true", "data-loading": "true", "aria-busy": "true" }`
 *   _(the first two come from `options.attrs`, the last two come from `base.loading`)_
 *
 * ---
 *
 * ### Pattern 4 — Category hook delegates to component hooks (two-level composition)
 *
 * **Used by:** `useFeedback` → `useBadge` / `useSpinner` / `useProgress`.
 *
 * Some categories use a two-tier model. A shared "category hook" (e.g.
 * `useFeedback`) calls `useBaseCompose` and returns a resolved result bag
 * (`feedbackClass`, `feedbackStyle`, `feedbackAttrs`, `rest`). Component hooks
 * within that category (e.g. `useBadge`) then call the category hook and
 * compose its output with their own component-specific classes using
 * `composeClass` — they do **not** call `useBaseCompose` a second time.
 *
 * ```ts
 * // badge.hook.ts — simplified
 * import { useFeedback } from "../feedback.hook";
 * import { composeClass } from "~/shared/base.hook";
 *
 * export function useBadge(props: BadgeProps) {
 *   const { count, max = 99, dot = false, ...feedbackProps } = props;
 *
 *   // useFeedback calls useBaseCompose internally
 *   const { feedbackClass, feedbackStyle, feedbackAttrs, rest } =
 *     useFeedback({ variant: "solid", color: "danger", ...feedbackProps });
 *
 *   return {
 *     Tag: "span" as const,
 *     props: {
 *       class:  composeClass(feedbackClass, "badge"),  // "feedback feedback--solid … badge"
 *       style:  feedbackStyle,
 *       ...feedbackAttrs,
 *       ...rest,
 *     },
 *     displayCount: count > max ? `${max}+` : String(count),
 *   };
 * }
 * ```
 *
 * **Rule of thumb:** `useBaseCompose` is always called **exactly once** per
 * component's render path, no matter how many hooks are involved.
 *
 * ---
 *
 * @param options - Component-built class tokens, style tokens, and extra attrs.
 * @param base - Remaining `BaseComponentProps` that the component hook did not consume.
 * @returns `{ className, style, attrs, rest, spacing }` — ready to spread onto the root element.
 *
 * @see {@link composeClass} — joins class token arrays into a space-separated string
 * @see {@link composeStyle} — joins style token arrays into a semicolon-separated string
 * @see {@link resolveColorRole} — turns a `ColorRole` into 7 CSS-variable assignments
 */
export function useBaseCompose(
  options: BaseComposeOptions,
  base?: BaseComponentProps,
) {
  // Strip all known non-DOM base props so they never appear as HTML attributes.
  const {
    v, 
    bg,
    motion, 
    mDistance, 
    action, 
    target,
    testId,
    loading: baseLoading, 
    disabled: baseDisabled, 
    class: baseClass, 
    style: baseStyle,
    // Extract spacing props
    p, px, py, pt, pr, pb, pl,
    m, mx, my, mt, mr, mb, ml,
    ...rest
  } = (base ?? {}) as BaseComponentProps;

  const isDisabled = options.disabled ?? baseDisabled;
  const isLoading  = options.loading  ?? baseLoading;

  const motionData = motion ? getMotionAttrs(motion) : null;
  const motionStyles: string[] = [];
  
  if (mDistance) {
    if (mDistance.startsWith("x") && !isNaN(Number(mDistance.slice(1)))) {
      motionStyles.push(`--m--scale: ${mDistance.slice(1)}`);
    } else {
      motionStyles.push(`--m--dist: ${mDistance}`);
    }
  }

  const bgVars = bg ? resolveColorRole(bg, "bg") : [];
 
  // Determine component prefix automatically from options.prefix or the first className token
  const classPrefix = options.className?.find(c => typeof c === "string" && c.length > 0) || "base";
  const prefix = options.prefix ?? classPrefix;

  const spacingStyles = resolveSpacingStyles(
    { p, px, py, pt, pr, pb, pl, m, mx, my, mt, mr, mb, ml },
    prefix
  );

  const className = composeClass(...(options.className ?? []), baseClass);
  const style     = composeStyle(
    ...(options.style ?? []),
    ...bgVars,
    ...spacingStyles,
    motionData?.enterStyle,
    ...motionStyles,
    baseStyle
  );
  const attrs: Record<string, unknown> = {
    ...(v          ? { "data-visual":  v }      : {}),
    ...(testId     ? { "data-testid":  testId } : {}),
    ...(isLoading  ? { "data-loading": "true", "aria-busy": "true" } : {}),
    ...(isDisabled ? { "aria-disabled": "true", "data-disabled": "" } : {}),
    ...(action     ? { "data-action":  action } : {}),
    ...(target     ? { "data-target":  target } : {}),
    // data-motion: presence flag for @media (prefers-reduced-motion) in motion.css
    ...(motionData ? { "data-motion":  "" }     : {}),
    // data-m-exit + data-m-exit-dur: read by mountMotionDismiss()
    ...(motionData?.exitAttrs ?? {}),
    ...options.attrs,
  };
  return { className, style, attrs, rest };
}

/**
 * Resolves a color role into a full set of CSS custom property assignments
 * scoped to a given channel prefix.
 *
 * Usage:
 *   ...resolveColorRole("primary", "data--color")
 *
 * Emits:
 *   --data--color--subtle: var(--primary--subtle)
 *   --data--color--muted:  var(--primary--muted)
 *   --data--color--base:   var(--primary--base)
 *   --data--color--vivid:  var(--primary--vivid)
 *   --data--color--deep:   var(--primary--deep)
 *   --data--color--border: var(--primary--border)
 *   --data--color--text:   var(--primary--text)
 *
 * Component CSS then reads whichever shade is semantically appropriate:
 *   border-color:     var(--data--color--border)
 *   background-color: var(--data--color--subtle)
 *   color:            var(--data--color--text)
 *
 * Roles without vivid/deep defined (success, danger, warning, info currently)
 * produce empty var() references — CSS ignores them safely.
 */
export function resolveColorRole(role: ColorRole, channel: string): string[] {
  return [
    `--${channel}--subtle: var(--${role}--subtle)`,
    `--${channel}--muted:  var(--${role}--muted)`,
    `--${channel}--base:   var(--${role}--base)`,
    `--${channel}--vivid:  var(--${role}--vivid)`,
    `--${channel}--deep:   var(--${role}--deep)`,
    `--${channel}--border: var(--${role}--border)`,
    `--${channel}--text:   var(--${role}--text)`,
  ];
}

if (process.env.NODE_ENV === "development") {
  const assert = (cond: boolean, msg: string) => { if (!cond) throw new Error(`resolveColorRole: ${msg}`); };
  const _result = resolveColorRole("primary", "data--color");
  assert(_result.length === 7, "7 channel strings emitted");
  const _suffixes = ["subtle", "muted", "base", "vivid", "deep", "border", "text"] as const;
  assert(
    _suffixes.every((s, i) => (_result[i] ?? "").startsWith(`--data--color--${s}:`)),
    "channel names: --{channel}--{suffix}",
  );
  assert(
    _suffixes.every((s, i) => (_result[i] ?? "").includes(`var(--primary--${s})`)),
    "var references: var(--{role}--{suffix})",
  );
}